export interface CountryOption {
  code: string;
  name: string;
}

export interface RegionOption {
  code: string;
  name: string;
}

export const COUNTRIES: CountryOption[] = [
  { code: "CA", name: "Canada" },
  { code: "US", name: "United States" },
];

export const PROVINCES_CANADA: RegionOption[] = [
  { code: "BC", name: "British Columbia" },
  { code: "AB", name: "Alberta" },
  { code: "ON", name: "Ontario" },
  { code: "QC", name: "Quebec" },
  { code: "MB", name: "Manitoba" },
  { code: "SK", name: "Saskatchewan" },
  { code: "NS", name: "Nova Scotia" },
  { code: "NB", name: "New Brunswick" },
  { code: "NL", name: "Newfoundland & Labrador" },
  { code: "PE", name: "Prince Edward Island" },
];

export const STATES_US: RegionOption[] = [
  { code: "CA", name: "California" },
  { code: "NY", name: "New York" },
  { code: "TX", name: "Texas" },
  { code: "WA", name: "Washington" },
  { code: "FL", name: "Florida" },
  { code: "IL", name: "Illinois" },
  { code: "PA", name: "Pennsylvania" },
  { code: "OH", name: "Ohio" },
  { code: "GA", name: "Georgia" },
  { code: "NC", name: "North Carolina" },
  { code: "MI", name: "Michigan" },
  { code: "NJ", name: "New Jersey" },
  { code: "VA", name: "Virginia" },
  { code: "MA", name: "Massachusetts" },
];

export const CITIES_BY_REGION: Record<string, string[]> = {
  // Canada Provinces
  BC: [
    "Coquitlam",
    "Vancouver",
    "Burnaby",
    "Surrey",
    "Richmond",
    "Victoria",
    "Kelowna",
    "Abbotsford",
    "Langley",
    "Port Coquitlam",
    "New Westminster",
    "North Vancouver",
    "West Vancouver",
    "Delta",
    "Nanaimo",
    "Kamloops",
    "Prince George",
    "Chilliwack",
    "Maple Ridge",
  ],
  AB: [
    "Calgary",
    "Edmonton",
    "Red Deer",
    "Lethbridge",
    "St. Albert",
    "Medicine Hat",
    "Grande Prairie",
    "Airdrie",
    "Spruce Grove",
    "Leduc",
  ],
  ON: [
    "Toronto",
    "Ottawa",
    "Mississauga",
    "Brampton",
    "Hamilton",
    "London",
    "Markham",
    "Vaughan",
    "Kitchener",
    "Windsor",
    "Richmond Hill",
    "Burlington",
    "Oshawa",
    "Barrie",
    "Guelph",
  ],
  QC: [
    "Montreal",
    "Quebec City",
    "Laval",
    "Gatineau",
    "Longueuil",
    "Sherbrooke",
    "Saguenay",
    "Levis",
    "Trois-Rivieres",
    "Terrebonne",
  ],
  MB: ["Winnipeg", "Brandon", "Steinbach", "Thompson", "Portage la Prairie"],
  SK: ["Saskatoon", "Regina", "Prince Albert", "Moose Jaw", "Swift Current"],
  NS: ["Halifax", "Sydney", "Truro", "New Glasgow", "Glace Bay"],
  NB: ["Moncton", "Saint John", "Fredericton", "Dieppe", "Miramichi"],
  NL: ["St. John's", "Mount Pearl", "Corner Brook", "Conception Bay South"],
  PE: ["Charlottetown", "Summerside", "Stratford", "Cornwall"],

  // US States
  CA: [
    "Los Angeles",
    "San Francisco",
    "San Diego",
    "San Jose",
    "Sacramento",
    "Fresno",
    "Long Beach",
    "Oakland",
    "Bakersfield",
    "Anaheim",
    "Irvine",
    "Santa Ana",
    "Riverside",
    "Stockton",
    "Chula Vista",
  ],
  NY: [
    "New York City",
    "Buffalo",
    "Rochester",
    "Yonkers",
    "Syracuse",
    "Albany",
    "New Rochelle",
    "Cheektowaga",
    "Mount Vernon",
    "Schenectady",
  ],
  TX: [
    "Houston",
    "San Antonio",
    "Dallas",
    "Austin",
    "Fort Worth",
    "El Paso",
    "Arlington",
    "Corpus Christi",
    "Plano",
    "Lubbock",
  ],
  WA: [
    "Seattle",
    "Spokane",
    "Tacoma",
    "Vancouver",
    "Bellevue",
    "Kent",
    "Everett",
    "Renton",
    "Spokane Valley",
    "Federal Way",
  ],
  FL: [
    "Miami",
    "Orlando",
    "Tampa",
    "Jacksonville",
    "St. Petersburg",
    "Hialeah",
    "Port St. Lucie",
    "Cape Coral",
    "Tallahassee",
    "Fort Lauderdale",
  ],
  IL: ["Chicago", "Aurora", "Joliet", "Naperville", "Rockford", "Springfield"],
  PA: ["Philadelphia", "Pittsburgh", "Allentown", "Erie", "Reading", "Scranton"],
  OH: ["Columbus", "Cleveland", "Cincinnati", "Toledo", "Akron", "Dayton"],
  GA: ["Atlanta", "Augusta", "Columbus", "Macon", "Savannah", "Athens"],
  NC: ["Charlotte", "Raleigh", "Greensboro", "Durham", "Winston-Salem", "Fayetteville"],
  MI: ["Detroit", "Grand Rapids", "Warren", "Sterling Heights", "Lansing", "Ann Arbor"],
  NJ: ["Newark", "Jersey City", "Paterson", "Elizabeth", "Lakewood", "Edison"],
  VA: ["Virginia Beach", "Chesapeake", "Norfolk", "Richmond", "Newport News", "Alexandria"],
  MA: ["Boston", "Worcester", "Springfield", "Cambridge", "Lowell", "Brockton"],
};
